<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'title' => 'MacBook Pro 14',
                'slug' => 'macbook-pro-14',
                'summary' => '<p>MacBook Pro 14</p>',
                'description' => '<p>MacBook Pro 14</p>',
                'photo' => '/storage/photos/1/MacBook Pro 14.jpg',
                'stock' => 5,
                'size' => '',
                'condition' => 'new',
                'status' => 'active',
                'price' => 21000000.00,
                'discount' => 5.00,
                'is_featured' => 0,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Macbook Air M3 13 inch 2024 8CPU 10GPU 24GB - 1TB sạc 70W',
                'slug' => 'macbook-air-m3-13-inch-2024-8cpu-10gpu-24gb-1tb-sac-70w',
                'summary' => '<p>Macbook Air M3 - Chip Apple M3, RAM 16GB, SSD 512GB</p>',
                'description' => '<p>Macbook Air M3 với hiệu năng vượt trội, thiết kế mỏng nhẹ</p>',
                'photo' => '/storage/photos/1/thumbs/laptop1.png',
                'stock' => 9,
                'size' => '',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 15000000.00,
                'discount' => 20.00,
                'is_featured' => 0,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'MacBook Air M1 256GB 2020',
                'slug' => 'macbook-air-m1-256gb-2020',
                'summary' => '<p>MacBook Air M1 256GB 2020</p>',
                'description' => '<p>MacBook Air M1 với chip M1 mạnh mẽ, RAM 8GB, SSD 256GB</p>',
                'photo' => '/storage/photos/1/thumbs/laptop2.png',
                'stock' => 9,
                'size' => '',
                'condition' => 'default',
                'status' => 'active',
                'price' => 30000000.00,
                'discount' => 10.00,
                'is_featured' => 0,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tai nghe chụp tai chống ồn Apple AirPods Max 2024',
                'slug' => 'tai-nghe-chup-tai-chong-on-apple-airpods-max-2024',
                'summary' => '<p>Tai nghe chụp tai chống ồn Apple AirPods Max 2024</p>',
                'description' => '<p>Tai nghe AirPods Max với chống ồn chủ động, âm thanh Hi-Fi</p>',
                'photo' => '/storage/photos/1/admin-icn.png',
                'stock' => 9,
                'size' => '',
                'condition' => 'default',
                'status' => 'active',
                'price' => 2000.00,
                'discount' => 0.00,
                'is_featured' => 0,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'iPad Pro M4 11 inch Wifi 256GB',
                'slug' => 'ipad-pro-m4-11-inch-wifi-256gb',
                'summary' => '<p>iPad Pro M4 11 inch Wifi 256GB</p>',
                'description' => '<p>iPad Pro M4 với chip M4 mạnh mẽ, màn hình 11 inch</p>',
                'photo' => '/storage/photos/1/thumbs/Screenshot_11.png',
                'stock' => 5,
                'size' => '',
                'condition' => 'new',
                'status' => 'active',
                'price' => 20000000.00,
                'discount' => 5.00,
                'is_featured' => 0,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tai nghe Bluetooth Apple AirPods 4',
                'slug' => 'tai-nghe-bluetooth-apple-airpods-4',
                'summary' => '<p>Tai nghe AirPod 4 - Giải trí sống động với âm thanh không gian cá nhân hóa</p>',
                'description' => '<p>AirPods 4 với chip H2, âm thanh không gian, chống nước IP54</p>',
                'photo' => '/storage/photos/1/sample_image.jpg',
                'stock' => 5,
                'size' => '',
                'condition' => 'default',
                'status' => 'active',
                'price' => 3488999.00,
                'discount' => 5.00,
                'is_featured' => 0,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Chuột không dây Genius Ergo 8100S',
                'slug' => 'chuot-khong-day-genius-ergo-8100s',
                'summary' => '<p>Chuột không dây Genius Ergo 8100S - 1600 DPI</p>',
                'description' => '<p>Chuột không dây với cảm biến quang học 1600 DPI chính xác</p>',
                'photo' => '/storage/photos/1/thumbs/phukien.png',
                'stock' => 5,
                'size' => '',
                'condition' => 'new',
                'status' => 'active',
                'price' => 450000.00,
                'discount' => 10.00,
                'is_featured' => 0,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bàn phím Apple Magic Keyboard 2021 MK2A3',
                'slug' => 'ban-phim-apple-magic-keyboard-2021-mk2a3',
                'summary' => '<p>Bàn phím Apple Magic Keyboard 2021 – Thiết kế gọn nhẹ, tinh tế</p>',
                'description' => '<p>Magic Keyboard với thiết kế hiện đại, kết nối Bluetooth</p>',
                'photo' => '/storage/photos/1/logo.png',
                'stock' => 5,
                'size' => '',
                'condition' => 'new',
                'status' => 'active',
                'price' => 3990000.00,
                'discount' => 10.00,
                'is_featured' => 0,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}
